### ISSUE TITLE
[feat] WritingView TCA 적용

### ISSUE THREAD

**Issue by beanbeen0** [TEAM-ALOM/plda-iOS#19]
## 👀 Issue
WritingView 부터 TCA를 적용합니다
### ✅ Todo
- [x] Tuist Image 접근
- [x] 배경이미지 코드 수정
- [ ] 폰트 코드 수정
- [x] ButtonStyle 폴더 정리
- [ ] WritingView TCA 적용
